### ISSUE TITLE
Thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by hendi** [mimblewimble/grin-miner#104]
```Jan 08 08:39:23.088 DEBG Mining: Plugin 0 - Device 0 (CPU) at Cuck(at)oo29 - Status: OK : Last Graph time: 3.279676162s; Graphs per second: 0.305 - Total Attempts: 95
Jan 08 08:39:23.088 DEBG Mining: Plugin 1 - Device 0 (GeForce GTX 1080) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.310326999s; Graphs per second: 3.222 - Total Attempts: 980
Jan 08 08:39:23.088 INFO Mining: Cuck(at)oo at 3.527315494702129 gps (graphs per second)
Jan 08 08:39:23.095 DEBG solver_thread - solver_loop_rx got msg: Pause
Jan 08 08:39:23.095 DEBG solver_thread - solver_loop_rx got msg: Resume
Jan 08 08:39:23.113 DEBG solver_thread - solver_loop_rx got msg: Pause
Jan 08 08:39:23.113 DEBG solver_thread - solver_loop_rx got msg: Resume
Jan 08 08:39:25.000 DEBG Received message: 3db6afe6b31a3fbd9dfd8d87baea9fbc2f25797d0a7e1036980f757f09d20058600d52be3169908b14bafef4daaee766b54d321e0ed48f4466343f3a6df5d2ec007f9ab1daf0713bd8\
911af3aae709072b73bf347bdfbf8d73d2adc6f89c03d60160433377c937c44cfcd77e9d68814ec95f8a66735c7fc509ea66e3baf59eb39b488f823d08052880973dc56faaf929b893090000000000015e32000000000000eac3000000004\
3bb87670000036a"},"error":null}

Jan 08 08:39:25.009 ERRO
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("trailing characters", line: 1, column: 2)': libcore/result.rs:1009stack backtrace:
   0:     0x5603d9f4d77d - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x5603d9f4c992 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5603d9f4ca09 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5603d9f21550 - grin_miner_util::logger::send_panic_to_log::{{closure}}::hfa11a4ae48705f01
   4:     0x5603d9f76c76 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x5603d9f767c1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x5603d9f766a5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5603d9fbd36c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x5603d9e2de2e - core::result::unwrap_failed::h1c5f2e219d7250f7
   9:     0x5603d9e2a9a2 - grin_miner::client::Controller::run::hf6ec02a19759b853
  10:     0x5603d9e45fa3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc2dc56f797d05443
  11:     0x5603d9e55408 - std::panicking::try::do_call::h1befc41c5608b207
  12:     0x5603d9f86d09 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x5603d9e5d367 - <F as alloc::boxed::FnBox<A>>::call_box::hd5dba00b916309b4
  14:     0x5603d9f740cd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x5603d9f65425 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f21646ba6da - start_thread
  17:     0x7f21641cb88e - __clone
  18:                0x0 - <unknown>


Jan 08 08:39:26.090 DEBG Mining: Plugin 0 - Device 0 (CPU) at Cuck(at)oo29 - Status: OK : Last Graph time: 3.279676162s; Graphs per second: 0.305 - Total Attempts: 95
Jan 08 08:39:26.090 DEBG Mining: Plugin 1 - Device 0 (GeForce GTX 1080) at Cuck(at)oo29 - Status: OK : Last Graph time: 0.309867315s; Graphs per second: 3.227 - Total Attempts: 990
```

**Comment by jaakkokoo** [comment]
Does grin-miner.toml file exists in the directory from which you're running grin-miner?

**Comment by hashmap** [comment]
Stratum server sends an invalid message obv, but we must not panic in this case

**Comment by pascalbreg** [comment]
My issue was resolved by getting the pools address right.

**Comment by quentinlesceller** [comment]
Old issue, closing. Feel free to reopen if this is still relevant.
