### ISSUE TITLE
Cuda Cuckaroo29 fails in binary release 1.0.0

### ISSUE THREAD

**Issue by hashmap** [mimblewimble/grin-miner#138]
When I built from the sources it works on this machine

```
Jan 16 10:19:00.263 INFO This is Grin-Miner version 1.0.0 (git v1.0.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
Jan 16 10:19:00.263 DEBG Built with profile "release", features "CURSIVE, DEFAULT, OCL_CUCKAROO, OCL_CUCKATOO, OPENCL, TUI" on Tue, 15 Jan 2019 14:42:47 GMT.
Jan 16 10:19:00.263 DEBG Starting solvers
Jan 16 10:19:00.263 DEBG No mining plugin dir provided by config. Using default plugin dir: "/home/ubuntu/grin-miner-v1.0.0/plugins"
Jan 16 10:19:00.263 DEBG Loading miner plugin: /home/ubuntu/grin-miner-v1.0.0/plugins/cuckaroo_cuda_29.cuckooplugin
Jan 16 10:19:00.264 DEBG Loading miner plugin: /home/ubuntu/grin-miner-v1.0.0/plugins/cuckaroo_cuda_29.cuckooplugin
Jan 16 10:19:00.273 ERRO
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x56090d3f62cd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x56090d3f54e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x56090d3f5559 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x56090d3ca0c0 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h8679019da915e120
   4:     0x56090d420ba6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x56090d4206f1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x56090d4205d5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x56090d46729c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x56090d4671cb - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:     0x56090d3aec29 - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::h1ec5e06c5bc82d6f
  10:     0x56090d3b2e73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ef7653c5992be1c
  11:     0x56090d3b3078 - std::panicking::try::do_call::h9c7bc7d910af5df6
  12:     0x56090d430c39 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x56090d3bab1d - <F as alloc::boxed::FnBox<A>>::call_box::hbbcdff5dd5e0e5b7
  14:     0x56090d41dffd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x56090d40f315 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f82af5c46da - start_thread
  17:     0x7f82af0d588e - __clone
  18:                0x0 - <unknown>
```

**Comment by hashmap** [comment]
I found it happens if Cuda 9 is installed on the machine, I will update docs.
