### ISSUE TITLE
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by aleqx** [mimblewimble/grin-miner#143]
I'm getting an error immediately upon launch on 1.0.0 (same as 0.5.2). After this error the miner does connect to the pool defined in `grin-miner.toml`, it exchanges messages, but doesn't do any work or submit any shares ever. It just stays idle and talks to the pool ...

Log and config below. Ubuntu 16.04 x64. CUDA 9.2. GTX1070 (13 on this motherboard). GrinGoldMiner works fine with the same settings (url, user, pass).

```
# ./grin-miner
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x558b48e0f2cd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x558b48e0e4e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x558b48e0e559 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x558b48de30c0 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h8679019da915e120
   4:     0x558b48e39ba6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:     0x558b48e396f1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:     0x558b48e395d5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x558b48e8029c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:     0x558b48e801cb - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:     0x558b48dc7c29 - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::h1ec5e06c5bc82d6f
  10:     0x558b48dcbe73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ef7653c5992be1c
  11:     0x558b48dcc078 - std::panicking::try::do_call::h9c7bc7d910af5df6
  12:     0x558b48e49c39 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x558b48dd3b1d - <F as alloc::boxed::FnBox<A>>::call_box::hbbcdff5dd5e0e5b7
  14:     0x558b48e36ffd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:     0x558b48e28315 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f4159bba6b9 - start_thread
  17:     0x7f41596da3dc - clone
  18:                0x0 - <unknown>


Jan 16 06:41:52.831 WARN Connection Status: Connected to Grin server at servers-eu.rig.rent:3322.
Jan 16 06:41:52.843 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"login","params":{"agent":"grin-miner","login":"<snip>","pass":"<snip>"}}
Jan 16 06:41:52.843 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
Jan 16 06:41:54.023 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:41:54.023 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)

Jan 16 06:41:57.011 DEBG Received response with id: 486
Jan 16 06:41:57.011 INFO Got a job at height 538 and difficulty 1
Jan 16 06:41:57.051 DEBG Miner received message: ReceivedJob(538, 0, 1, "0001000000000000021a000000005c3eb5f60000087f535a708b62df78596dfc0f3f643c2d96faff36a348e9036b67f6cc8ee5e51b6aa9e74902301366150d12e763f36f3a80ea8741a94d5c5839d47ed1969963b40dada9f9b17c3927677e8d64e8c00a46756f542a824ececc2a26503b779e099d5b4c1cefa8f69733255d78d5aaa5a409de3000b9d04678378f664397e60e45f1029577115f46d3332691e4c5b065d45b4fc25cddffe5e5795beb756bc200000000000000000000000000000000000000000000000000000000000000000000000000000431000000000000043100000059b14ce04500000644")
Jan 16 06:41:57.051 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:41:57.051 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:00.084 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:00.084 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:03.004 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:03.004 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:06.024 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:06.024 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:09.093 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:09.093 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:12.041 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:12.041 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:15.065 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:15.065 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:18.098 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:18.098 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:21.050 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:21.050 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:22.006 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"status","params":null}
Jan 16 06:42:23.006 DEBG Received message: {"id":"486","jsonrpc":"2.0","method":"status","result":{"accepted":0,"difficulty":1,"height":0,"id":"0","rejected":0,"stale":0},"error":null}
Jan 16 06:42:23.006 DEBG Received response with id: 486
Jan 16 06:42:23.006 INFO Status for worker 0 - Height: 0, Difficulty: 1, (0/0/0)
Jan 16 06:42:24.070 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf -
Total Attempts: 0
Jan 16 06:42:24.070 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:27.003 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf -
Total Attempts: 0
Jan 16 06:42:27.003 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:30.031 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf -
Total Attempts: 0
Jan 16 06:42:30.031 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:33.063 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:33.063 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:35.008 DEBG Received message: {"id":"486","jsonrpc":"2.0","method":"getjobtemplate","result":{"difficulty":1,"height":539,"job_id":0,"pre_pow":"0001000000000000021b000000005c3eb63900001227ccf666ce9aa47e862035cd04f8f235e67eda343726e6437d0dfd81f28b9f0cd9e43cdfb1fe3a06a4bd0bbc967bfdad6554b5dfed2cf4f338dda760e5382ee261f1186d84df321695c9f2b440c5bb0f1ff6ac37ffb777f566da45026d0ba07a66e00c8efa5d41a330615b46929daeea39ccd87a2199558486a225446086ca2b9bedd4bc30f9324fc60543dc6c69a49fd8928137bf77bb66466f90a20500000000000000000000000000000000000000000000000000000000000000000000000000000434000000000000043400000059d09d920c00000644"},"error":null}

Jan 16 06:42:35.008 DEBG Received response with id: 486
Jan 16 06:42:35.008 INFO Got a job at height 539 and difficulty 1
Jan 16 06:42:35.076 DEBG Miner received message: ReceivedJob(539, 0, 1, "0001000000000000021b000000005c3eb63900001227ccf666ce9aa47e862035cd04f8f235e67eda343726e6437d0dfd81f28b9f0cd9e43cdfb1fe3a06a4bd0bbc967bfdad6554b5dfed2cf4f338dda760e5382ee261f1186d84df321695c9f2b440c5bb0f1ff6ac37ffb777f566da45026d0ba07a66e00c8efa5d41a330615b46929daeea39ccd87a2199558486a225446086ca2b9bedd4bc30f9324fc60543dc6c69a49fd8928137bf77bb66466f90a20500000000000000000000000000000000000000000000000000000000000000000000000000000434000000000000043400000059d09d920c00000644")
Jan 16 06:42:35.076 DEBG Pause message sent
Jan 16 06:42:35.076 DEBG Resume message sent
Jan 16 06:42:36.080 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:36.080 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:39.000 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:39.000 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:42.044 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 16 06:42:42.044 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 16 06:42:45.041 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
..
..
..
```

.toml file

```
# sed '/^#/d;/^$/d' grin-miner.toml
[logging]
log_to_stdout = true
stdout_log_level = "Info"
log_to_file = true
file_log_level = "Debug"
log_file_path = "grin-miner.log"
log_file_append = true
[mining]
run_tui = false
stratum_server_addr = "servers-eu.rig.rent:3322"
stratum_server_login = "<snip>"
stratum_server_password = "<snip>"
stratum_server_tls_enabled = false
[[mining.miner_plugin_config]]
plugin_name = "cuckaroo_cuda_29"
[mining.miner_plugin_config.parameters]
device = 12
```

**Comment by gagarin55** [comment]
Me too ;(

**Comment by apruden2008** [comment]
Not sure if this is it, but I had a similar issue because my .toml file wasn't in the same directory as my executable

**Comment by invis87** [comment]
Wow, Thanks so much!!! I spent 2 days to understand why grin-miner throws: ```thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value'```
The problem was in driver (I use Ubuntu 16.04 - tried to build from sources, tried to use binary version - nothing helps). But the problem was in nvidia driver... @hashmap thanks! maybe you should add this info to main README.md?

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
