### ISSUE TITLE
Could not build grin-miner on digitalocean dropelet

### ISSUE THREAD

**Issue by rllola** [mimblewimble/grin-miner#16]
Hi, 

I am trying to build grin-miner on a digitalocean dropelet on Ubuntu 16.04. I have installed what has been written on the build instruction. Then I try to build the project.

```
root@grin:~/grin-miner# cargo build
warning: An explicit [[bin]] section is specified in Cargo.toml which currently
disables Cargo from automatically inferring other binary targets.
This inference behavior will change in the Rust 2018 edition and the following
files will be included as a binary target:

* /root/grin-miner/src/bin/types.rs
* /root/grin-miner/src/bin/plugin.rs
* /root/grin-miner/src/bin/client.rs
* /root/grin-miner/src/bin/mining.rs
* /root/grin-miner/src/bin/stats.rs

This is likely to break cargo build or cargo test as these files may not be
ready to be compiled as a binary target today. You can future-proof yourself
and disable this warning by adding `autobins = false` to your [package]
section. You may also move the files to a location where Cargo would not
automatically infer them to be a target, such as in subfolders.

For more information on this warning you can consult
https://github.com/rust-lang/cargo/issues/5330
   Compiling log v0.3.9
   Compiling thread_local v0.3.5
   Compiling ncurses v5.93.0
error: failed to run custom build command for `ncurses v5.93.0`
process didn't exit successfully: `/root/grin-miner/target/debug/build/ncurses-617b5826ad9ec715/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rustc-link-lib=ncursesw
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")

--- stderr
/root/grin-miner/target/debug/build/ncurses-a19907545286d318/out/chtype_size.c:6:21: fatal error: ncurses.h: No such file or directory
compilation terminated.
thread 'main' panicked at '/root/grin-miner/target/debug/build/ncurses-a19907545286d318/out/chtype_size failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Look like the there in some issue finding what I am running looking at `TARGET = Some("x86_64-unknown-linux-gnu")` ? Maybe because digitalocean has a customize their ubuntu image ? I have no idea to be honest...

**Comment by rllola** [comment]
Using backtrace.

```
thread 'main' panicked at '/root/grin-miner/target/debug/build/ncurses-a19907545286d318/out/chtype_size failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:809
  10: build_script_build::check_chtype_size
             at ./build.rs:86
  11: build_script_build::main
             at ./build.rs:48
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start
```

**Comment by bladedoyle** [comment]
I think the key error here is:
`fatal error: ncurses.h: No such file or directory`

Please install the following 2 ncurses development packages:
```
libncurses5-dev
libncursesw5-dev
```

**Comment by rllola** [comment]
Indeed I was missing those 2.
I installed : 
```
libncurses5
libncursesw5
```
I copied it from the grin Dockerfile thinking it would do the job.

I have made a gist in case someone want to build for ubuntu 16.04 
https://gist.github.com/rllola/ef4cb2340edb4d918108140d7bd7529b

Thank you
