### ISSUE TITLE
thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"'

### ISSUE THREAD

**Issue by llchan** [mimblewimble/grin-miner#200]
This is a new one that I havent seen before, not sure what this PoisonError is but it sounds undesirable.

```
thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': src/libcore/result.rs:1009stack backtrace:
   0:     0x562d240005ad - backtrace::backtrace::trace::h16f4d19e5ed7ab6a
   1:     0x562d23fff6d2 - backtrace::capture::Backtrace::new::h53b2d57f7dd6d113
   2:     0x562d23fcac10 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h2e69af416f76170f
   3:     0x562d2402b3f9 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   4:     0x562d2402aea1 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                        at src/libstd/panicking.rs:398
   5:     0x562d2402ad85 - rust_begin_unwind
                        at src/libstd/panicking.rs:325
   6:     0x562d240411bc - core::panicking::panic_fmt::h4d67173bc68f6d5a
                        at src/libcore/panicking.rs:95
   7:     0x562d23fc118e - core::result::unwrap_failed::h8894dd25e88c37ed
   8:     0x562d23fb9ba7 - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::hb530a0f8610f2331
   9:     0x562d23fc3000 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6a320c51a159670a
  10:     0x562d23fbde55 - std::panicking::try::do_call::h80e525874bf54b30
  11:     0x562d2403ace9 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  12:     0x562d23fc451d - <F as alloc::boxed::FnBox<A>>::call_box::hd00eec36871403a3
  13:     0x562d2402ebcd - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  14:     0x7fc183a3f6da - start_thread
  15:     0x7fc18355088e - __clone
  16:                0x0 - <unknown>
```

**Comment by quentinlesceller** [comment]
Closing. Feel free to reopen if this is still relevant.
