### ISSUE TITLE
fatal runtime error:failed to initiate panic. error5

### ISSUE THREAD

**Issue by jeromelinjianlong** [mimblewimble/grin-miner#204]

**Comment by jeromelinjianlong** [comment]
fatal runtime error:failed to initiate panic. error5

anyone can help me?

**Comment by ptrk01** [comment]
I am facing the same issue. It happens after I installed the miner and at running ./target/release/grin-miner. I use Ubuntu 19.10.

Here is an excerpt of the grin-miner.log:

Nov 14 12:13:50.467 DEBG Starting solvers
Nov 14 12:13:50.467 DEBG No mining plugin dir provided by config. Using default plugin dir: "/root/mwgrinpool/grin-miner/target/release/plugins"
Nov 14 12:13:50.467 DEBG Loading miner plugin: /root/mwgrinpool/grin-miner/target/release/plugins/cuckaroo_cpu_avx2_29.cuckooplugin
Nov 14 12:13:50.471 DEBG Loading miner plugin: /root/mwgrinpool/grin-miner/target/release/plugins/cuckaroo_cpu_avx2_29.cuckooplugin
Nov 14 12:13:50.525 ERRO
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': src/libcore/option.rs:378stack backtrace:
   0:     0x558dba40851d - backtrace::backtrace::trace::hf511fe4c8ac187c5
   1:     0x558dba407802 - <backtrace::capture::Backtrace as core::default::Default>::default::h5c7fe621c83cacba
   2:     0x558dba3d5450 - grin_miner_util::logger::send_panic_to_log::{{closure}}::ha82aba03c04b16ea
   3:     0x558dba42e00b - std::panicking::rust_panic_with_hook::h825f041245da8739
                        at src/libstd/panicking.rs:477
   4:     0x558dba42dac1 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                        at src/libstd/panicking.rs:380
   5:     0x558dba42d9b5 - rust_begin_unwind
                        at src/libstd/panicking.rs:307
   6:     0x558dba449ea9 - core::panicking::panic_fmt::h527855ce0bc891f6
                        at src/libcore/panicking.rs:85
   7:     0x558dba449de8 - core::panicking::panic::h2f49f09cf859b728
                        at src/libcore/panicking.rs:49
   8:     0x558dba431da8 - core::option::Option<T>::unwrap::h336396d3ba79c43c
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/macros.rs:12
                         - panic_unwind::imp::cleanup::hd215375862d38759
                        at src/libpanic_unwind/gcc.rs:91
                         - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:83
   9:     0x558dba3cd5d5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h40778e34dee6a79f
  10:     0x558dba4204ee - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  11:     0x558dba43142f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                        at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
                         - std::sys_common::thread::start_thread::h557b0c2dc4449562
                        at src/libstd/sys_common/thread.rs:13
                         - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba

**Comment by quentinlesceller** [comment]
@ptrk01 Looks like a different issue. Are you launching the miner from the directory with the config file? (i.e. `grin-miner.toml`)

**Comment by ptrk01** [comment]
@quentinlesceller Yes, I do. 

I followed these steps https://pastebin.com/raw/f3AFztWj
