### ISSUE TITLE
thread 'unnamed' panicked at 'called `Option::unwrap()`

### ISSUE THREAD

**Issue by chinatimmy** [mimblewimble/grin-miner#252]
```
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': cuckoo-miner/src/miner/miner.rs:95   0: grin_miner_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
   2: rust_begin_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:419
   3: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:111
   4: core::panicking::panic
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:54
   5: cuckoo_miner::miner::miner::CuckooMiner::solver_thread
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
   8: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys/unix/thread.rs:87
   9: start_thread
  10: clone
```

```
Aug 05 07:21:08.082 DEBG Mining: Plugin 0 - Device 0 () at Cuckarooz0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Aug 05 07:21:08.083 INFO Mining: Cucka*oo* at 0 gps (graphs per second)
Aug 05 07:21:11.086 DEBG Mining: Plugin 0 - Device 0 () at Cuckarooz0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Aug 05 07:21:11.086 INFO Mining: Cucka*oo* at 0 gps (graphs per second)

```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   45C    P0    36W / 151W |    413MiB /  8116MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1070    Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   35C    P8     5W / 151W |      2MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by quentinlesceller** [comment]
Hi @chinatimmy can you tell me:
1. Did you build from source?
2. What's your configuration (grin-miner.toml)?

**Comment by chinatimmy** [comment]
Hello @quentinlesceller this error occurred when compiled from source and with downloaded bin file on Ubuntu 20.04

```
[[mining.miner_plugin_config]]
plugin_name = "cuckarooz_cuda_29"
[mining.miner_plugin_config.parameters]
device = 0

[[mining.miner_plugin_config]]
plugin_name = "cuckarooz_cuda_29"
[mining.miner_plugin_config.parameters]
device = 1
```

I've also disabled an enabled each device as well as changed the plugins to other cuckaroo plugins.

**Comment by quentinlesceller** [comment]
Did you uncomment the line in https://github.com/mimblewimble/grin-miner/blob/master/Cargo.toml to build the cuda plugins?

**Comment by chinatimmy** [comment]
Yes I did, I've compiled it successfully earlier on in the project and it ran.

**Comment by quentinlesceller** [comment]
Mmm I've no idea what's happening. Looks like the solver cannot create the context here https://github.com/mimblewimble/grin-miner/blob/master/cuckoo-miner/src/miner/miner.rs#L95. Can you give me ssh access to this machine so I can debug this bug? 
Or give me a way to reproduce this somehow. Thanks!
