### ISSUE TITLE
Miner fails on unwrap, "missing field job_id"

### ISSUE THREAD

**Issue by beaver-tooth** [mimblewimble/grin-miner#27]
## Steps:
0. start up grin
1. clone grin-miner
2. cd grin-miner
3. cargo build
4. target/debug/grin-miner

## Details
**rust version:** 1.27.0
* Fully synced
* 11 peers
* mostly certain port forwarding set-up for port 13415

## Error
```
Jul 12 21:21:50.254 INFO This is Grin-Miner version 0.3.0 (git e6dd6e4), built for x86_64-apple-darwin by rustc 1.27.0 (3eda71b00 2018-06-19).
Jul 12 21:21:51.259 WARN Connection Status: Connected to Grin server at 127.0.0.1:13416.
Jul 12 21:21:52.454 ERRO 
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `job_id`", line: 0, column: 0)': libcore/result.rs:945stack backtrace:
   0:        0x104af4e34 - backtrace::backtrace::trace::hc8e132fcef8d0bfc
                        at /Users/beavertooth/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x104aeff6c - backtrace::capture::Backtrace::new_unresolved::h2de564d7dbc71823
                        at /Users/beavertooth/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x104aefebe - backtrace::capture::Backtrace::new::hf446536b3bc80d5a
                        at /Users/beavertooth/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x1046f9f3c - grin_miner_util::logger::send_panic_to_log::{{closure}}::h89891c311a91eefc
                        at util/src/logger.rs:120
   4:        0x104b23384 - std::panicking::rust_panic_with_hook::hc2253a5bcda7eda7
                        at libstd/panicking.rs:467
   5:        0x104b22e70 - std::panicking::begin_panic_fmt::h2a4ecdf0c76cf1c3
                        at libstd/panicking.rs:350
   6:        0x104b22e32 - _rust_begin_unwind
                        at libstd/panicking.rs:328
   7:        0x104b5af85 - core::panicking::panic_fmt::hb253bce78d883c0b
                        at libcore/panicking.rs:71
   8:        0x1047320ee - core::result::unwrap_failed::h74105e4ba40d88e1
                        at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x1044cb762 - <core::result::Result<T, E>>::unwrap::hc29d8fd21a57083f
                        at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10:        0x1044e61d8 - grin_miner::client::Controller::handle_request::he7a245faad984c3b
                        at src/bin/client.rs:234
  11:        0x1044ea201 - grin_miner::client::Controller::run::hfb63abaf67629af6
                        at src/bin/client.rs:433
  12:        0x104510b1f - grin_miner::main::{{closure}}::ha2345b2dd6baf3b6
                        at src/bin/grin_miner.rs:171
  13:        0x10456d104 - std::sys_common::backtrace::__rust_begin_short_backtrace::h14b27324bdd351f9
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  14:        0x1044d117b - std::thread::Builder::spawn::{{closure}}::{{closure}}::h935cb74e746044e5
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:409
  15:        0x104539864 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6cbdc9fb0784b710
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:305
  16:        0x1045112c4 - std::panicking::try::do_call::he531f4b797a9fb5f
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:310
  17:        0x104b2ea7e - ___rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  18:        0x104510e19 - std::panicking::try::hc317bb4a1d74f878
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
  19:        0x104539944 - std::panic::catch_unwind::h539b4a59c466f846
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:374
  20:        0x1044d0ef8 - std::thread::Builder::spawn::{{closure}}::hbc1e89a4a10bfa07
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:408
  21:        0x1044d11d5 - <F as alloc::boxed::FnBox<A>>::call_box::h4978502977e14a11
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  22:        0x104b1fa57 - std::sys_common::thread::start_thread::h4258ce81cea6ecca
                        at libstd/sys_common/thread.rs:24
  23:        0x104b0f888 - std::sys::unix::thread::Thread::new::thread_start::h7ac7d9b68b94f18d
                        at libstd/sys/unix/thread.rs:90
  24:     0x7fff541be660 - __pthread_body
  25:     0x7fff541be50c - __pthread_start
```

**Comment by beaver-tooth** [comment]
May be similar to this issue: https://www.grin-forum.org/t/miner-stuck-in-starting-miner-awaiting-first-graph-time/366/6

**Comment by BravoIndia** [comment]
Same

`Jul 13 12:04:57.040 DEBG Received request type: job
Jul 13 12:04:57.266 ERRO 
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `job_id`", line: 0, column: 0)': libcore/result.rs:945stack backtrace:
   0:        0x1098d2174 - backtrace::backtrace::trace::h15eb31d27a677210
                        at /Users/student/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x1098cd0cc - backtrace::capture::Backtrace::new_unresolved::h0f301ff91537984c
                        at /Users/student/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x1098cd01e - backtrace::capture::Backtrace::new::h1b01bc9e357b4898
                        at /Users/student/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x1094dc46c - grin_miner_util::logger::send_panic_to_log::{{closure}}::h720d1047b6290c2c
                        at util/src/logger.rs:120
   4:        0x1099007a4 - std::panicking::rust_panic_with_hook::hd069cce60c0084f5
                        at libstd/panicking.rs:467
   5:        0x109900290 - std::panicking::begin_panic_fmt::h143ce20914b91de2
                        at libstd/panicking.rs:350
   6:        0x109900252 - _rust_begin_unwind
                        at libstd/panicking.rs:328
   7:        0x1099383a5 - core::panicking::panic_fmt::h10c6d4aa5d882d41
                        at libcore/panicking.rs:71
   8:        0x1095150fe - core::result::unwrap_failed::he0988b926cac0115
                        at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x1092b00b2 - <core::result::Result<T, E>>::unwrap::hfdf2a41f6fe99623
                        at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10:        0x1092ca308 - grin_miner::client::Controller::handle_request::he8e62e356f44d0b8
                        at src/bin/client.rs:234
  11:        0x1092ce081 - grin_miner::client::Controller::run::h1fc1550a1a4b56eb
                        at src/bin/client.rs:427
  12:        0x1092f499f - grin_miner::main::{{closure}}::h9cd3693aeb2a277b
                        at src/bin/grin_miner.rs:171
  13:        0x109350be4 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha44a95bc4c9c9e92
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  14:        0x1092b52ab - std::thread::Builder::spawn::{{closure}}::{{closure}}::h53884947ecd6b173
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:409
  15:        0x10931d2b4 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h50576325028dfef8
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:305
  16:        0x1092f5164 - std::panicking::try::do_call::hd6b6f9a6030ae785
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:310
  17:        0x10990be9e - ___rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  18:        0x1092f4e19 - std::panicking::try::h3ea3012217923812
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
  19:        0x10931d454 - std::panic::catch_unwind::he61e630499d33586
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:374
  20:        0x1092b4d18 - std::thread::Builder::spawn::{{closure}}::h45ef62e0c46c4788
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:408
  21:        0x1092b5305 - <F as alloc::boxed::FnBox<A>>::call_box::h67f3b6c7781bb51e
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  22:        0x1098fce77 - std::sys_common::thread::start_thread::hf39c8bd91f08cd93
                        at libstd/sys_common/thread.rs:24
  23:        0x1098ecca8 - std::sys::unix::thread::Thread::new::thread_start::h27c7af0fa85baf64
                        at libstd/sys/unix/thread.rs:90
  24:     0x7fff53d51660 - __pthread_body
  25:     0x7fff53d5150c - __pthread_start
`

**Comment by BravoIndia** [comment]
Same issue looks like

```
Jul 13 12:04:57.040 DEBG Received request type: job
Jul 13 12:04:57.266 ERRO 
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `job_id`", line: 0, column: 0)': libcore/result.rs:945stack backtrace:
   0:        0x1098d2174 - backtrace::backtrace::trace::h15eb31d27a677210
                        at /Users/student/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:        0x1098cd0cc - backtrace::capture::Backtrace::new_unresolved::h0f301ff91537984c
                        at /Users/student/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:        0x1098cd01e - backtrace::capture::Backtrace::new::h1b01bc9e357b4898
                        at /Users/student/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:        0x1094dc46c - grin_miner_util::logger::send_panic_to_log::{{closure}}::h720d1047b6290c2c
                        at util/src/logger.rs:120
   4:        0x1099007a4 - std::panicking::rust_panic_with_hook::hd069cce60c0084f5
                        at libstd/panicking.rs:467
   5:        0x109900290 - std::panicking::begin_panic_fmt::h143ce20914b91de2
                        at libstd/panicking.rs:350
   6:        0x109900252 - _rust_begin_unwind
                        at libstd/panicking.rs:328
   7:        0x1099383a5 - core::panicking::panic_fmt::h10c6d4aa5d882d41
                        at libcore/panicking.rs:71
   8:        0x1095150fe - core::result::unwrap_failed::he0988b926cac0115
                        at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x1092b00b2 - <core::result::Result<T, E>>::unwrap::hfdf2a41f6fe99623
                        at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10:        0x1092ca308 - grin_miner::client::Controller::handle_request::he8e62e356f44d0b8
                        at src/bin/client.rs:234
  11:        0x1092ce081 - grin_miner::client::Controller::run::h1fc1550a1a4b56eb
                        at src/bin/client.rs:427
  12:        0x1092f499f - grin_miner::main::{{closure}}::h9cd3693aeb2a277b
                        at src/bin/grin_miner.rs:171
  13:        0x109350be4 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha44a95bc4c9c9e92
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  14:        0x1092b52ab - std::thread::Builder::spawn::{{closure}}::{{closure}}::h53884947ecd6b173
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:409
  15:        0x10931d2b4 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h50576325028dfef8
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:305
  16:        0x1092f5164 - std::panicking::try::do_call::hd6b6f9a6030ae785
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:310
  17:        0x10990be9e - ___rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  18:        0x1092f4e19 - std::panicking::try::h3ea3012217923812
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
  19:        0x10931d454 - std::panic::catch_unwind::he61e630499d33586
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:374
  20:        0x1092b4d18 - std::thread::Builder::spawn::{{closure}}::h45ef62e0c46c4788
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:408
  21:        0x1092b5305 - <F as alloc::boxed::FnBox<A>>::call_box::h67f3b6c7781bb51e
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:638
  22:        0x1098fce77 - std::sys_common::thread::start_thread::hf39c8bd91f08cd93
                        at libstd/sys_common/thread.rs:24
  23:        0x1098ecca8 - std::sys::unix::thread::Thread::new::thread_start::h27c7af0fa85baf64
                        at libstd/sys/unix/thread.rs:90
  24:     0x7fff53d51660 - __pthread_body
  25:     0x7fff53d5150c - __pthread_start
```
