### ISSUE TITLE
SIGSEGV from cuckatoo_mean_cpu plugin; compat. plugin runs fine

### ISSUE THREAD

**Issue by OpticFlowX** [mimblewimble/grin-miner#46]
Date: 19. Oct. 2018

Immediately after `cuckatoo_mean_cpu` plug-in starts mining, a segmentation fault occurs. At the same configuration `cuckatoo_mean_compat_cpu` works without problems. Tested Tromp's standalone solver `mean29x8` without any issues.

**Reproducibility**: every time

**System**: VirtualBox VM with Debian 9.5, GCC 6.3.0, 8 GB RAM, i7-4790k CPU, 4 virtual cores

**Config**: 
[[mining.miner_plugin_config]]
edge_bits = 29
type_filter = "cuckatoo_mean_cpu"
[mining.miner_plugin_config.device_parameters.0]
NUM_THREADS = 4

**Backtrace** from GDB:

```
Thread 14 "mining_controll" received signal SIGSEGV, Segmentation fault.(LWP 19471)

(gdb) info threads
  Id   Target Id         Frame
  1    Thread 0x7ffff7fe70c0 (LWP 19452) "grin-miner" 0x00007ffff73667dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  3    Thread 0x7ffff63fe700 (LWP 19457) "grin-miner" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7ffff5bff700 (LWP 19459) "grin-miner" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7ffff65ff700 (LWP 19460) "ui" 0x00007ffff6e7f67d in poll () at ../sysdeps/unix/syscall-template.S:84
  7    Thread 0x7ffff55ff700 (LWP 19461) "mining_controll" 0x00007ffff73667dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  8    Thread 0x7ffff53fe700 (LWP 19462) "client_controll" 0x00007ffff73667dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  11   Thread 0x7ffff49ff700 (LWP 19471) "mining_controll" 0x00007ffff73667dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  12   Thread 0x7ffff3dff700 (LWP 19472) "mining_controll" 0x00007ffff6e5828d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  13   Thread 0x7ffff31ff700 (LWP 19473) "mining_controll" clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:80
* 14   Thread 0x7fff0c5ff700 (LWP 19474) "mining_controll" edgetrimmer::genUnodes (this=this@entry=0x7ffff31fd970, id=id@entry=0, uorv=uorv@entry=0)
    at /home/sa/.cargo/git/checkouts/cuckoo-miner-4752934f0f1f2bfe/7862dfe/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.hpp:347
  15   Thread 0x7fff0bdfe700 (LWP 19475) "mining_controll" _mm256_load_si256(long long __vector(4) const*) (__P=<optimized out>) at /usr/lib/gcc/x86_64-linux-gnu/6/include/avxintrin.h:884
  16   Thread 0x7fff0b5fd700 (LWP 19476) "mining_controll" clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:80
(gdb) bt
#0  edgetrimmer::genUnodes (this=this@entry=0x7ffff31fd970, id=id@entry=0, uorv=uorv@entry=0)
    at /home/sa/.cargo/git/checkouts/cuckoo-miner-4752934f0f1f2bfe/7862dfe/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.hpp:347
#1  0x00007ffff4035942 in edgetrimmer::trimmer (id=0, this=0x7ffff31fd970) at /home/sa/.cargo/git/checkouts/cuckoo-miner-4752934f0f1f2bfe/7862dfe/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.hpp:1010
#2  etworker (vp=<optimized out>) at /home/sa/.cargo/git/checkouts/cuckoo-miner-4752934f0f1f2bfe/7862dfe/src/cuckoo_sys/plugins/cuckoo/src/cuckatoo/mean.hpp:1049
#3  0x00007ffff735d494 in start_thread (arg=0x7fff0c5ff700) at pthread_create.c:333
#4  0x00007ffff6e88acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by OpticFlowX** [comment]
I'm closing the issue since it no longer appears in the latest version (as of 26. Oct.).
