### ISSUE TITLE
Miner crashes cryptically when configuration file can't be found

### ISSUE THREAD

**Issue by pcdinh** [mimblewimble/grin-miner#53]
With the latest code checked out, I got my grin-miner crashed after building and running it

```
grintest@grintest:~/grin-miner/target/debug$ RUST_BACKTRACE=1 ./grin-miner
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: <core::option::Option<T>>::unwrap
             at libcore/macros.rs:20
  10: grin_miner::main
             at src/bin/grin_miner.rs:106
  11: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

All of Grin plugins have been built successfully

```
grintest@grintest:~/grin-miner/target/debug/plugins$ ls -al
total 3384
drwxrwxr-x 2 grintest grintest   4096 Thg 1  2 00:06 .
drwxrwxr-x 9 grintest grintest   4096 Thg 1  2 00:07 ..
-rwxrwxr-x 1 grintest grintest 279688 Thg 1  2 00:06 cuckatoo_lean_cpu_19.cuckooplugin
-rwxrwxr-x 1 grintest grintest 279688 Thg 1  2 00:06 cuckatoo_lean_cpu_29.cuckooplugin
-rwxrwxr-x 1 grintest grintest 279688 Thg 1  2 00:06 cuckatoo_lean_cpu_30.cuckooplugin
-rwxrwxr-x 1 grintest grintest 473712 Thg 1  2 00:06 cuckatoo_mean_avx2_cpu_19.cuckooplugin
-rwxrwxr-x 1 grintest grintest 464488 Thg 1  2 00:06 cuckatoo_mean_avx2_cpu_29.cuckooplugin
-rwxrwxr-x 1 grintest grintest 464440 Thg 1  2 00:06 cuckatoo_mean_avx2_cpu_30.cuckooplugin
-rwxrwxr-x 1 grintest grintest 403168 Thg 1  2 00:06 cuckatoo_mean_compat_cpu_19.cuckooplugin
-rwxrwxr-x 1 grintest grintest 393664 Thg 1  2 00:06 cuckatoo_mean_compat_cpu_29.cuckooplugin
-rwxrwxr-x 1 grintest grintest 393408 Thg 1  2 00:06 cuckatoo_mean_compat_cpu_30.cuckooplugin

```

```
grintest@grintest:~/grin-miner/target/debug$ ls -al
total 41364
drwxrwxr-x   9 grintest grintest     4096 Thg 1  2 00:07 .
drwxrwxr-x   3 grintest grintest     4096 Thg 1  2 00:07 ..
drwxrwxr-x  40 grintest grintest     4096 Thg 1  2 00:06 build
-rw-rw-r--   1 grintest grintest        0 Thg 1  2 00:06 .cargo-lock
drwxrwxr-x   2 grintest grintest    36864 Thg 1  2 00:07 deps
drwxrwxr-x   2 grintest grintest     4096 Thg 1  2 00:06 examples
drwxrwxr-x 151 grintest grintest    12288 Thg 1  2 00:06 .fingerprint
-rwxrwxr-x   2 grintest grintest 42268624 Thg 1  2 00:07 grin-miner
-rw-rw-r--   1 grintest grintest     6201 Thg 1  2 00:07 grin-miner.d
drwxrwxr-x   8 grintest grintest     4096 Thg 1  2 00:07 incremental
drwxrwxr-x   2 grintest grintest     4096 Thg 1  2 00:06 native
drwxrwxr-x   2 grintest grintest     4096 Thg 1  2 00:06 plugins
```

```
grintest@grintest:~/grin-miner/target/debug$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

grintest@grintest:~/grin-miner/target/debug$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

grintest@grintest:~/grin-miner/target/debug$ rustc --version
rustc 1.30.0 (da5f414c2 2018-10-24)

```

Thanks

**Comment by pcdinh** [comment]
After moving grin-miner.toml from base source directory to target/debug I finally got grin-miner up and running

**Comment by pcdinh** [comment]
Please close this ticket
