### ISSUE TITLE
Miner crashes, all plugins compiled, TOML in same directory

### ISSUE THREAD

**Issue by ivanmladek** [mimblewimble/grin-miner#55]
With the latest code checked out, I got my grin-miner crashed after building and running it

```
root@ubuntu1:~/code/grin-miner/target/debug# RUST_BACKTRACE=1  ./grin-miner 
Starting Grin-Miner from config file at: /root/code/grin-miner/target/debug/grin-miner.toml
Nov 16 02:05:44.476 INFO This is Grin-Miner version 0.4.0 (git 648e49e), built for x86_64-unknown-linux-gnu by rustc 1.30.0 (da5f414c2 2018-10-24).
Nov 16 02:05:45.480 WARN Connection Status: Connected to Grin server at 127.0.0.1:13416.
Nov 16 02:05:46.239 ERRO 
thread 'client_controller' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)': libcore/result.rs:1009stack backtrace:
   0:     0x560a4a40ad75 - backtrace::backtrace::libunwind::trace::hf44c22fad7d74627
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h0749eb5dd04566a8
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x560a4a40550e - backtrace::capture::Backtrace::new_unresolved::h6e4fa3794f901826
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x560a4a40546c - backtrace::capture::Backtrace::new::h5326c2d66bbc8ea2
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:     0x560a4a34aaf6 - grin_miner_util::logger::send_panic_to_log::{{closure}}::h5ecd98e14f0940ad
                        at util/src/logger.rs:120
   4:     0x560a4a430133 - std::panicking::rust_panic_with_hook::h0e12cb2fc86d00fa
                        at libstd/panicking.rs:481
   5:     0x560a4a42fc99 - std::panicking::continue_panic_fmt::h141671b29fe0e27d
                        at libstd/panicking.rs:391
   6:     0x560a4a42fb95 - rust_begin_unwind
                        at libstd/panicking.rs:326
   7:     0x560a4a47c65b - core::panicking::panic_fmt::h429a06507aba9228
                        at libcore/panicking.rs:77
   8:     0x560a49ff7598 - core::result::unwrap_failed::hd6ae9e563385636c
                        at libcore/macros.rs:26
   9:     0x560a49ff3ca6 - <core::result::Result<T, E>>::unwrap::hf28dcb19de66dc72
                        at libcore/result.rs:808
  10:     0x560a49fd1fff - grin_miner::client::Controller::run::h96a0ff8906e279d0
                        at src/bin/client.rs:428
  11:     0x560a4a009056 - grin_miner::main::{{closure}}::h23ab55701e3c1068
                        at src/bin/grin_miner.rs:193
  12:     0x560a4a0651f6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7cfbb90f9fe08817
                        at libstd/sys_common/backtrace.rs:136
  13:     0x560a49fe3804 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h244c8bad06959c06
                        at libstd/thread/mod.rs:409
  14:     0x560a4a052ec4 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc30c052f6e5ac879
                        at libstd/panic.rs:313
  15:     0x560a49fae489 - std::panicking::try::do_call::hcd2078af6910971c
                        at libstd/panicking.rs:310
  16:     0x560a4a4506b9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  17:     0x560a49fae1c6 - std::panicking::try::hd129106fda848293
                        at libstd/panicking.rs:289
  18:     0x560a4a052fb6 - std::panic::catch_unwind::h81939697f420e343
                        at libstd/panic.rs:392
  19:     0x560a49fe32ba - std::thread::Builder::spawn::{{closure}}::h4fd05ad28e1d704c
                        at libstd/thread/mod.rs:408
  20:     0x560a49fe38c2 - <F as alloc::boxed::FnBox<A>>::call_box::h22af13ed2f126136
                        at liballoc/boxed.rs:646
  21:     0x560a4a44154a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::hb77935aee02382da
                        at libstd/sys_common/thread.rs:24
  22:     0x560a4a430895 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75
                        at libstd/sys/unix/thread.rs:90
  23:     0x7f04b39357fb - start_thread
  24:     0x7f04b344bb5e - clone
  25:                0x0 - <unknown>


Thread 'client_controller' panicked with message:
"called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)"
See grin.log for further details.
```

All of Grin plugins have been built successfully

```
root@ubuntu1:~/code/grin-miner/target/debug# ls -al plugins/
total 8328
drwxr-xr-x 2 root root    4096 Nov 14 06:39 .
drwxr-xr-x 9 root root    4096 Nov 16 02:02 ..
-rwxr-xr-x 1 root root  327368 Nov 14 18:18 cuckatoo_lean_cpu_19.cuckooplugin
-rwxr-xr-x 1 root root  327368 Nov 14 18:18 cuckatoo_lean_cpu_29.cuckooplugin
-rwxr-xr-x 1 root root  327368 Nov 14 18:18 cuckatoo_lean_cpu_30.cuckooplugin
-rwxr-xr-x 1 root root  762520 Nov 14 18:18 cuckatoo_lean_cuda_29.cuckooplugin
-rwxr-xr-x 1 root root  762520 Nov 14 18:18 cuckatoo_lean_cuda_30.cuckooplugin
-rwxr-xr-x 1 root root  546168 Nov 14 18:18 cuckatoo_mean_avx2_cpu_19.cuckooplugin
-rwxr-xr-x 1 root root  539712 Nov 14 18:18 cuckatoo_mean_avx2_cpu_29.cuckooplugin
-rwxr-xr-x 1 root root  539232 Nov 14 18:18 cuckatoo_mean_avx2_cpu_30.cuckooplugin
-rwxr-xr-x 1 root root  439352 Nov 14 18:18 cuckatoo_mean_compat_cpu_19.cuckooplugin
-rwxr-xr-x 1 root root  431840 Nov 14 18:18 cuckatoo_mean_compat_cpu_29.cuckooplugin
-rwxr-xr-x 1 root root  431384 Nov 14 18:18 cuckatoo_mean_compat_cpu_30.cuckooplugin
-rwxr-xr-x 1 root root 1529592 Nov 14 18:18 cuckatoo_mean_cuda_29.cuckooplugin
-rwxr-xr-x 1 root root 1529632 Nov 14 18:18 cuckatoo_mean_cuda_30.cuckooplugin
```

```
root@ubuntu1:~/code/grin-miner/target/debug# ls -al
total 41396
drwxr-xr-x   9 root root     4096 Nov 16 02:02 .
drwxr-xr-x   4 root root     4096 Nov 12 23:29 ..
drwxr-xr-x  44 root root     4096 Nov 12 20:27 build
-rw-r--r--   1 root root        0 Oct 30 01:06 .cargo-lock
drwxr-xr-x   2 root root    40960 Nov 14 18:18 deps
drwxr-xr-x   2 root root     4096 Oct 30 01:06 examples
drwxr-xr-x 161 root root    12288 Nov 12 20:27 .fingerprint
-rwxr-xr-x   2 root root 42251976 Nov 14 18:18 grin-miner
-rw-r--r--   1 root root     6053 Oct 30 01:08 grin-miner.d
-rw-r--r--   1 root root    30948 Nov 16 02:05 grin-miner.log
-rw-r--r--   1 root root     4515 Nov 14 18:48 grin-miner.toml
drwxr-xr-x  13 root root     4096 Nov 14 06:40 incremental
drwxr-xr-x   2 root root     4096 Oct 30 01:06 native
drwxr-xr-x   2 root root     4096 Nov 14 06:39 plugins
```

```
root@ubuntu1:~/code/grin-miner/target/debug# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
root@ubuntu1:~/code/grin-miner/target/debug# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88
root@ubuntu1:~/code/grin-miner/target/debug# gcc --version
gcc (Ubuntu 4.8.5-4ubuntu6) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@ubuntu1:~/code/grin-miner/target/debug# 
root@ubuntu1:~/code/grin-miner/target/debug# rustc --version
rustc 1.30.0 (da5f414c2 2018-10-24)
```

Please note grin-miner.toml IS already in the same directory as grin-miner as per https://github.com/mimblewimble/grin-miner/issues/53

Any ideas?

**Comment by ivanmladek** [comment]
Update to grin server 0.4.1 resolved this.
