### ISSUE TITLE
Improve error handling when incorrect GPU device is incorrect

### ISSUE THREAD

**Issue by illera88** [mimblewimble/grin-miner#59]
If the device is incorrect for the CUDA miner, this ugly error shows up and the "mining" keeps going on:

```
user@miner2:~/grin-miner$ ./target/release/grin-miner
Starting Grin-Miner from config file at: /home/user/grin-miner/grin-miner.toml
Dec 04 08:26:24.514 INFO This is Grin-Miner version 0.4.0 (git c4a321e), built for x86_64-unknown-linux-gnu by rustc 1.30.1 (1433507eb 2018-11-07).
Dec 04 08:26:26.376 WARN Connection Status: Connected to Grin server at 12.34.56.78:13416.
Dec 04 08:26:26.664 INFO Got a new job: JobTemplate { height: 67397, job_id: 6, difficulty: 1, pre_pow: "00010000000000010745000000005c063a320e7116b8b4a27e03548662edb815e05586a8bf2c19e8bfa98b7f3461bd090ab29eda50332eb52285c463a6cbf846b2f26643651d484f8f7a45a487eca48ab599c6e141b9644e5884a3cb8f3e7d38489a890428c56f27d09146a54ddf0a492dd29005f4f9d6e53bbf0b9d912ea034bce8d63f86ef489a821c4a37e71cecfd9a21a5f941c12d5786867adaa05bc4d9b6b03f46710e54ed2863fc0b7c98bc64dee116b20f317388ae89cec228a07444c1d9461ded11f14684310a5397071f166966000000000005824d000000000003c757000000010f620aa2000008b9" }
Dec 04 08:26:26.665 INFO Got a job at height 67397 and difficulty 1
Dec 04 08:26:26.935 ERRO
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:345stack backtrace:
   0:     0x564e23bf552c - backtrace::backtrace::trace::hfd526ef98dddbf50
   1:     0x564e23bf47a2 - <backtrace::capture::Backtrace as core::default::Default>::default::h01baa1b5e98591f2
   2:     0x564e23bf4818 - backtrace::capture::Backtrace::new::h81868384ca0965cd
   3:     0x564e23bcb65f - grin_miner_util::logger::send_panic_to_log::{{closure}}::he5a9d0e936b5b830
   4:     0x564e23c064a3 - std::panicking::rust_panic_with_hook::h86e619a638415243
                        at libstd/panicking.rs:481
   5:     0x564e23c06009 - std::panicking::continue_panic_fmt::h2d2d2bfb065a70b2
                        at libstd/panicking.rs:391
   6:     0x564e23c05f05 - rust_begin_unwind
                        at libstd/panicking.rs:326
   7:     0x564e23c5cabb - core::panicking::panic_fmt::h2155aa66b67fe83c
                        at libcore/panicking.rs:77
   8:     0x564e23c5c9ea - core::panicking::panic::h9b4aaddfe00d4a7f
                        at libcore/panicking.rs:52
   9:     0x564e23b9f587 - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::hba63fd5e68a43948
  10:     0x564e23ba9932 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1242e5aae9d2faa7
  11:     0x564e23ba34e7 - std::panicking::try::do_call::hcae9be1af1346476
  12:     0x564e23c26a69 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  13:     0x564e23bab976 - <F as alloc::boxed::FnBox<A>>::call_box::heb63b0369a1b76d2
  14:     0x564e23c178fa - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hfedf8d10954bca7a
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::h75d887c7d2cc4479
                        at libstd/sys_common/thread.rs:24
  15:     0x564e23c06bb5 - std::sys::unix::thread::Thread::new::thread_start::h8414caee632bf9ed
                        at libstd/sys/unix/thread.rs:90
  16:     0x7fba7eb446da - start_thread
  17:     0x7fba7e65588e - __clone
  18:                0x0 - <unknown>


Thread 'unnamed' panicked with message:
"called `Option::unwrap()` on a `None` value"
See grin.log for further details.

```

**Comment by dimsav** [comment]
I get the same issue.

Ubuntu 16.04
NVIDIA GeForce 1080
