### ISSUE TITLE
Connection retry every 5 seconds stopped working

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-miner#98]
The grin-miner no longer reconnects if its connection to the server is broken.

Steps to reproduce:
1) Start a grin wallet listener
2) start a grin server with stratum server enabled
3) start a miner on that stratum server
The miner will connect and start mining.
4) stop the grin server (and stratum server)
The miner will lose its connection and say "Connection Status: Can't establish server connection to localhost:13416.  Will retry every 5 seconds."
5) start the grin server (and stratum server)

Expected:   The grin-miner should reconnect within the 5-second interval, and resume mining.

Actual:  The grin-miner remains disconnected with the same connection status message.

**Comment by bladedoyle** [comment]
Here are the grin-miner logs for the event:

```
Jan 02 23:05:33.004 ERRO Error reading message: ConnectionError("broken pipe")
Jan 02 23:05:33.112 DEBG Miner received message: StopJob
Jan 02 23:05:33.112 DEBG Stopping jobs
Jan 02 23:05:33.112 DEBG Pause message sent
Jan 02 23:05:33.157 DEBG solver_thread - solver_loop_rx got msg: Pause
Jan 02 23:05:33.220 WARN Connection Status: Can't establish server connection to mwfloopool.com:3333. Will retry every 5 seconds
Jan 02 23:05:33.231 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"login","params":{"agent":"grin-miner","login":"foo16","pass":"bar"}}
Jan 02 23:05:33.343 ERRO
thread 'client_controller' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:     0x5589ca27ebb6 - backtrace::backtrace::libunwind::trace::h4f1eb391823a5f81
                        at /home/bdoyle/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h6a83df765cc0adc5
                        at /home/bdoyle/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x5589ca2792c3 - backtrace::capture::Backtrace::new_unresolved::hde36ae9aafa6a496
                        at /home/bdoyle/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x5589ca27921d - backtrace::capture::Backtrace::new::h6c48d3430f353b80
                        at /home/bdoyle/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
   3:     0x5589ca1a5e87 - grin_miner_util::logger::send_panic_to_log::{{closure}}::hc308aa077f52697d
                        at util/src/logger.rs:120
   4:     0x5589ca2eca06 - std::panicking::rust_panic_with_hook::h71214e7ce0f7ac01
                        at libstd/panicking.rs:480
   5:     0x5589ca2ec551 - std::panicking::continue_panic_fmt::ha8b8442f4ea9bcac
                        at libstd/panicking.rs:390
   6:     0x5589ca2ec435 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5589ca33310c - core::panicking::panic_fmt::h0c93626b89c38af6
                        at libcore/panicking.rs:77
   8:     0x5589ca33303b - core::panicking::panic::h158c6e3285d6c3fb
                        at libcore/panicking.rs:52
   9:     0x5589c9e90aff - <core::option::Option<T>>::unwrap::hfaaabe534b19dedf
                        at libcore/macros.rs:20
  10:     0x5589c9e94afe - <grin_miner::client::Stream as std::io::Write>::write::hf6ebfd20836bcaf0
                        at src/bin/client.rs:82
  11:     0x5589c9e95e16 - grin_miner::client::Controller::send_message::ha640b0ceb646ce1f
                        at src/bin/client.rs:213
  12:     0x5589c9e96a13 - grin_miner::client::Controller::send_login::h815ff8d7963ad020
                        at src/bin/client.rs:263
  13:     0x5589c9e9c31b - grin_miner::client::Controller::run::hdcdd345660985d4b
                        at src/bin/client.rs:513
  14:     0x5589c9e569da - grin_miner::main::{{closure}}::hc9188e1152c62b8a
                        at src/bin/grin_miner.rs:206
  15:     0x5589c9ece506 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4b8a46842b717eab
                        at libstd/sys_common/backtrace.rs:136
  16:     0x5589c9eebdb4 - std::thread::Builder::spawn::{{closure}}::{{closure}}::had67f4079cfead58
                        at libstd/thread/mod.rs:409
  17:     0x5589c9e559c4 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h40a3d35dcf4e0334
                        at libstd/panic.rs:313
  18:     0x5589c9ea2039 - std::panicking::try::do_call::h942d551848ff4a72
                        at libstd/panicking.rs:310
  19:     0x5589ca2fcd19 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  20:     0x5589c9ea1917 - std::panicking::try::h783f6e619ccfd1af
                        at libstd/panicking.rs:289
  21:     0x5589c9e55b76 - std::panic::catch_unwind::h82ac0f5d81b44938
                        at libstd/panic.rs:392
  22:     0x5589c9eebb52 - std::thread::Builder::spawn::{{closure}}::he99c462a61ea8b5b
                        at libstd/thread/mod.rs:408
  23:     0x5589c9eebeb4 - <F as alloc::boxed::FnBox<A>>::call_box::h55c628e2df6dc440
                        at liballoc/boxed.rs:672
  24:     0x5589ca2e9e5d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::he3acfc8f1203786f
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h5213f803a61d7811
                        at libstd/sys_common/thread.rs:24
  25:     0x5589ca2daee5 - std::sys::unix::thread::Thread::new::thread_start::he89121f566d2a8c7
                        at libstd/sys/unix/thread.rs:90
  26:     0x7f26f824b6da - start_thread
  27:     0x7f26f7d5c88e - __clone
  28:                0x0 - <unknown>
```

**Comment by bladedoyle** [comment]
@quentinlesceller Can you please take a look?  The crash may be related to the recent TLS work you did?

**Comment by AvaGlobalgithub** [comment]
Excellent!

**Comment by elkimek** [comment]
I have similar issuue when trying to use release:

```
Jan 06 05:40:37.870 INFO This is Grin-Miner version 0.5.0 (git v0.5.0), built for x86_64-unknown-linux-gnu by rustc 1.31.1 (b6c32da9b 2018-12-18).
Jan 06 05:40:37.870 DEBG Built with profile "release", features "DEFAULT, OCL_CUCKATOO, OPENCL" on Fri, 04 Jan 2019 21:36:47 GMT.
Jan 06 05:40:37.870 DEBG Starting solvers
Jan 06 05:40:37.870 DEBG Loading miner plugin: /root/grin-miner/plugins/cuckaroo_cuda_29.cuckooplugin
Jan 06 05:40:37.880 DEBG Loading miner plugin: /root/grin-miner/plugins/cuckaroo_cuda_29.cuckooplugin
Jan 06 05:40:37.950 ERRO 
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': libcore/option.rs:355stack backtrace:
   0:        0xbdbd0413d - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:        0xbdbd03352 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:        0xbdbd033c9 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:        0xbdbcd7f20 - grin_miner_util::logger::send_panic_to_log::{{closure}}::hbdaceb72c390e91a
   4:        0xbdbd2e796 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   5:        0xbdbd2e2e1 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   6:        0xbdbd2e1c5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:        0xbdbd74e8c - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   8:        0xbdbd74dbb - core::panicking::panic::hca17aeb7dac42859
                        at libcore/panicking.rs:52
   9:        0xbdbcbcea8 - cuckoo_miner::miner::miner::CuckooMiner::solver_thread::h46da8fb40082b572
  10:        0xbdbcbf423 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9c9c29652760ec34
  11:        0xbdbcc1446 - std::panicking::try::do_call::h788bdc53df52f583
  12:        0xbdbd3e829 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:        0xbdbcc8d6d - <F as alloc::boxed::FnBox<A>>::call_box::h24adc29cb77df5ec
  14:        0xbdbd2bbed - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  15:        0xbdbd1cf45 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  16:     0x7f949a1116b9 - start_thread
  17:     0x7f9499c313dc - clone
  18:                0x0 - <unknown>


Jan 06 05:40:39.126 WARN Connection Status: Connected to Grin server at stratum.mwgrinpool.com:3333.
Jan 06 05:40:39.136 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"login","params":{"agent":"grin-miner","login":"Elkimek","pass":"editedpw"}}
Jan 06 05:40:39.136 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"getjobtemplate","params":null}
Jan 06 05:40:40.087 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:40:40.087 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:40:43.005 DEBG Received message: {"id":"276","jsonrpc":"2.0","method":"login","result":"ok","error":null}

Jan 06 05:40:43.005 DEBG Received response with id: 276
Jan 06 05:40:43.005 DEBG Received message: {"id":"276","jsonrpc":"2.0","method":"getjobtemplate","result":{"difficulty":1,"height":11857,"job_id":0,"pre_pow":"00010000000000002e51000000005c3186bc00816a64ce17ca135fe1e744aeb9b6548a9b9feb6c7dae45cb33f5db87bb6882684a04269f36e0d95d86e8e838e400d1a6b2d2d1b642c326c0802dc49278aded5a241e39ca2bf324362f51cfc6fdd26da62d70e45bbc677fd306aef609e9d0ec12a5fa1580437a64bb8039bfc5e4ea81cf5f1fe2b2247ba1635d550c2ef273343af6e4279fd514f01721d5773f275d8e0fee8ea64a56738053226a0f9740fd563d3b45a08003b59bc00187c14ebbfe6afbeff9dae12f39ca0d7fe115e68353290000000000011a8b000000000000bca1000000002506614f000001ff"},"error":null}

Jan 06 05:40:43.005 DEBG Received response with id: 276
Jan 06 05:40:43.005 INFO Got a job at height 11857 and difficulty 1
Jan 06 05:40:43.005 DEBG Received message: {"id":"276","jsonrpc":"2.0","method":"getjobtemplate","result":{"difficulty":1,"height":11857,"job_id":0,"pre_pow":"00010000000000002e51000000005c3186bc00816a64ce17ca135fe1e744aeb9b6548a9b9feb6c7dae45cb33f5db87bb6882684a04269f36e0d95d86e8e838e400d1a6b2d2d1b642c326c0802dc49278aded5a241e39ca2bf324362f51cfc6fdd26da62d70e45bbc677fd306aef609e9d0ec12a5fa1580437a64bb8039bfc5e4ea81cf5f1fe2b2247ba1635d550c2ef273343af6e4279fd514f01721d5773f275d8e0fee8ea64a56738053226a0f9740fd563d3b45a08003b59bc00187c14ebbfe6afbeff9dae12f39ca0d7fe115e68353290000000000011a8b000000000000bca1000000002506614f000001ff"},"error":null}

Jan 06 05:40:43.005 DEBG Received response with id: 276
Jan 06 05:40:43.006 INFO Got a job at height 11857 and difficulty 1
Jan 06 05:40:43.094 DEBG Miner received message: ReceivedJob(11857, 0, 1, "00010000000000002e51000000005c3186bc00816a64ce17ca135fe1e744aeb9b6548a9b9feb6c7dae45cb33f5db87bb6882684a04269f36e0d95d86e8e838e400d1a6b2d2d1b642c326c0802dc49278aded5a241e39ca2bf324362f51cfc6fdd26da62d70e45bbc677fd306aef609e9d0ec12a5fa1580437a64bb8039bfc5e4ea81cf5f1fe2b2247ba1635d550c2ef273343af6e4279fd514f01721d5773f275d8e0fee8ea64a56738053226a0f9740fd563d3b45a08003b59bc00187c14ebbfe6afbeff9dae12f39ca0d7fe115e68353290000000000011a8b000000000000bca1000000002506614f000001ff")
Jan 06 05:40:43.094 DEBG Pause message sent
Jan 06 05:40:43.094 DEBG Resume message sent
Jan 06 05:40:43.094 DEBG Miner received message: ReceivedJob(11857, 0, 1, "00010000000000002e51000000005c3186bc00816a64ce17ca135fe1e744aeb9b6548a9b9feb6c7dae45cb33f5db87bb6882684a04269f36e0d95d86e8e838e400d1a6b2d2d1b642c326c0802dc49278aded5a241e39ca2bf324362f51cfc6fdd26da62d70e45bbc677fd306aef609e9d0ec12a5fa1580437a64bb8039bfc5e4ea81cf5f1fe2b2247ba1635d550c2ef273343af6e4279fd514f01721d5773f275d8e0fee8ea64a56738053226a0f9740fd563d3b45a08003b59bc00187c14ebbfe6afbeff9dae12f39ca0d7fe115e68353290000000000011a8b000000000000bca1000000002506614f000001ff")
Jan 06 05:40:43.094 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:40:43.094 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:40:46.099 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:40:46.099 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:40:49.005 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:40:49.005 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:40:52.010 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:40:52.010 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:40:55.021 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:40:55.021 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:40:58.027 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:40:58.027 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:01.009 DEBG Received message: {"id":"276","jsonrpc":"2.0","method":"getjobtemplate","result":{"difficulty":1,"height":11858,"job_id":0,"pre_pow":"00010000000000002e52000000005c3186db0134869f39e84961b25f773cb690946cf66cb19641172cf9449df588e9b2ebba4db22448501ca257f06a08864d804e391406e2e2d386f313f4f9fbb1a21a95ddae5d2ae7dd9ea44ad8023079b568334bc95b4144dcd14d92d14d32f2b6aa12f30d1f90030bedbe2295cc43c6bbd5104a91b8c3876bd83c31cad5d0c087beb429e52790aec0444093d30715a3430cf5e12bc1dfe8795308e52bde116ee4b8c7803d3b45a08003b59bc00187c14ebbfe6afbeff9dae12f39ca0d7fe115e68353290000000000011a8d000000000000bca3000000002507dd30000001ff"},"error":null}

Jan 06 05:41:01.009 DEBG Received response with id: 276
Jan 06 05:41:01.009 INFO Got a job at height 11858 and difficulty 1
Jan 06 05:41:01.035 DEBG Miner received message: ReceivedJob(11858, 0, 1, "00010000000000002e52000000005c3186db0134869f39e84961b25f773cb690946cf66cb19641172cf9449df588e9b2ebba4db22448501ca257f06a08864d804e391406e2e2d386f313f4f9fbb1a21a95ddae5d2ae7dd9ea44ad8023079b568334bc95b4144dcd14d92d14d32f2b6aa12f30d1f90030bedbe2295cc43c6bbd5104a91b8c3876bd83c31cad5d0c087beb429e52790aec0444093d30715a3430cf5e12bc1dfe8795308e52bde116ee4b8c7803d3b45a08003b59bc00187c14ebbfe6afbeff9dae12f39ca0d7fe115e68353290000000000011a8d000000000000bca3000000002507dd30000001ff")
Jan 06 05:41:01.035 DEBG Pause message sent
Jan 06 05:41:01.035 DEBG Resume message sent
Jan 06 05:41:01.035 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:01.035 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:04.041 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:04.041 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:07.050 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:07.050 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:08.003 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"status","params":null}
Jan 06 05:41:09.009 DEBG Received message: {"id":"276","jsonrpc":"2.0","method":"status","result":{"accepted":0,"difficulty":1,"height":11858,"id":"0","rejected":0,"stale":0},"error":null}

Jan 06 05:41:09.009 DEBG Received response with id: 276
Jan 06 05:41:09.009 INFO Status for worker 0 - Height: 11858, Difficulty: 1, (0/0/0)
Jan 06 05:41:10.055 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:10.055 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:13.063 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:13.063 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:16.075 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:16.075 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:19.082 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:19.082 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:22.092 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:22.092 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:25.000 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:25.000 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:28.007 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:28.007 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:31.015 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:31.015 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:34.027 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:34.027 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:37.037 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:37.037 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:39.006 DEBG sending request: {"id":"0","jsonrpc":"2.0","method":"status","params":null}
Jan 06 05:41:40.049 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:40.049 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:41.009 DEBG Received message: {"id":"276","jsonrpc":"2.0","method":"status","result":{"accepted":0,"difficulty":1,"height":11858,"id":"0","rejected":0,"stale":0},"error":null}

Jan 06 05:41:41.009 DEBG Received response with id: 276
Jan 06 05:41:41.009 INFO Status for worker 0 - Height: 11858, Difficulty: 1, (0/0/0)
Jan 06 05:41:43.055 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:43.055 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:46.066 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:46.066 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:49.073 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:49.073 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:52.083 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:52.083 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:55.088 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:55.088 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:41:58.098 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:41:58.098 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:42:01.002 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:42:01.002 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:42:04.008 DEBG Mining: Plugin 0 - Device 0 () at Cuck(at)oo0 - Status: OK : Last Graph time: 0s; Graphs per second: inf - Total Attempts: 0
Jan 06 05:42:04.008 INFO Mining: Cuck(at)oo at 0 gps (graphs per second)
Jan 06 05:42:04.739 DEBG Client received message: Shutdown
Jan 06 05:42:04.739 DEBG Shutting down client controller
Jan 06 05:42:04.811 DEBG Miner received message: Shutdown
Jan 06 05:42:04.811 DEBG Stopping jobs and Shutting down mining controller
Jan 06 05:42:04.811 DEBG Stop message sent
```
Not sure but it seems we have same issue @bladedoyle ?

**Comment by bergr01** [comment]
Looks like adding self.stream = None; as a last line in the if block containing 'Will retry every x seconds' message seems to have the desired effect - i.e. when server is back up, miner re-established connection to it.
